@HostAddress = http://localhost:5272
@json = application/json
@apiKey = dXNlcjFAZXhhbXBsZS5jb206UGFzc3dvcmQxMjMh

GET {{HostAddress}}/api/hotels
Accept: application/json

###

POST {{HostAddress}}/api/hotels
Content-Type: application/json

{
  "name": "Hotel California",
  "address": "42 Sunset Boulevard",
  "city": "Los Angeles",
  "country": "USA",
  "rating": 5
}

###

@hotelId = 2

DELETE {{HostAddress}}/api/hotels/{{hotelId}}

###
GET {{HostAddress}}/api/hotels/{{hotelId}}
Accept: application/json

###
PUT {{HostAddress}}/api/hotels/{{hotelId}}
Content-Type: application/json

{
  "name": "Updated Hotel Name",
  "address": "Updated Address",
  "city": "Updated City",
  "country": "Updated Country",
  "rating": 4
}

###
GET {{HostAddress}}/api/countries
Accept: application/json
X-Api-Key: {{apiKey}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzNDcwNDhkZi0zMTk0LTRjYTMtYjNjNi0yMzcxOTYxMDgyMmIiLCJlbWFpbCI6Im5ld3VzZXJAZXhhbXBsZS5jb20iLCJqdGkiOiIzMmE5ZTVjYi1hNWM4LTQ2OWQtYTVjNy1jY2ZmZmI2ZTU5OTYiLCJuYW1lIjoiICIsImV4cCI6MTc4MzkzODE2OSwiaXNzIjoiSG90ZWxMaXN0aW5nQVBJIiwiYXVkIjoiSG90ZWxMaXN0aW5nQVBJQ2xpZW50In0.4Gy__p6fmV0JE0AbE86mnw-9ithfmaKjJPFnnm06Muc

###
POST {{HostAddress}}/api/auth/register
Content-Type: application/json

{
  "FirstName": "New",
  "LastName": "User",
  "email": "newuser3@example.com",
  "password": "Password123!"
}

###
POST {{HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "newuser@example.com",
  "password": "Password123!"
}

